name: supershoes
description: "Super Shoes"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  provider: ^6.1.2
  http: ^1.3.0
  flutter_secure_storage: ^9.0.0
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
